# Generated by Django 4.0.3 on 2022-03-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_alter_sleep_duration_time_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='duration_time_hours',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='duration_time_minutes',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sleep',
            name='duration_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
