# Generated by Django 4.0.3 on 2022-03-17 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='created_at',
            new_name='created_at_date',
        ),
        migrations.AddField(
            model_name='water',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
