# Generated by Django 4.0.3 on 2022-03-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0002_rename_created_at_water_created_at_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='real_value',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
