# Generated by Django 4.0.3 on 2022-03-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0003_water_real_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='real_value',
            field=models.IntegerField(null=True),
        ),
    ]
