# Generated by Django 4.0.3 on 2022-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_measurments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='week_rate',
            field=models.FloatField(default=0.5),
        ),
    ]
